/* AUTO-GENERATED by scripts/build.py — DO NOT EDIT */
/* app shell をキャッシュして、オフラインでも開けるようにする。

   版は app shell の中身のハッシュから決まる。手で上げる必要はない。
   中身が変われば版が変わり、古いキャッシュは activate で消える。
   file:// では Service Worker が動かないので、登録は index.html 側で弾いている。 */
const VERSION = 'decc6bef5fed';
const CACHE = 'god-thinking-' + VERSION;
const SHELL = [
  "./",
  "index.html",
  "manifest.webmanifest",
  "assets/css/tokens.css",
  "assets/css/base.css",
  "assets/css/layout.css",
  "assets/css/components.css",
  "assets/css/prose.css",
  "assets/js/dom.js",
  "assets/js/store.js",
  "assets/js/search.js",
  "assets/js/toc.js",
  "assets/js/router.js",
  "assets/js/app.js",
  "assets/js/views/partials.js",
  "assets/js/views/list.js",
  "assets/js/views/article.js",
  "assets/js/views/questions.js",
  "assets/js/views/matrix.js",
  "assets/js/views/mines.js",
  "data/studio.js",
  "data/hypotheses.js",
  "data/matrix.js",
  "data/questions.js",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/icon-maskable-512.png",
  "assets/icons/apple-touch-icon-180.png",
  "assets/icons/favicon-32.png"
];

self.addEventListener('install', function (ev) {
  ev.waitUntil(
    caches.open(CACHE)
      .then(function (c) {
        // **cache: 'reload' が要る。** 既定では addAll がブラウザの HTTP キャッシュを
        // 経由するため、版を上げても古いファイルがそのまま入りうる。
        // 実際それで、新しい版のキャッシュに古い matrix.js が入る事故が起きた。
        return c.addAll(SHELL.map(function (u) {
          return new Request(u, { cache: 'reload' });
        }));
      })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (ev) {
  ev.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        return k === CACHE ? null : caches.delete(k);
      }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('fetch', function (ev) {
  if (ev.request.method !== 'GET') return;
  ev.respondWith(
    caches.match(ev.request).then(function (hit) {
      if (hit) return hit;
      return fetch(ev.request).catch(function () {
        // 画面遷移はハッシュルーティングなので、外れたら index.html を返す
        if (ev.request.mode === 'navigate') return caches.match('index.html');
        throw new Error('offline');
      });
    })
  );
});
