"""仮説工房のビルド。

    python scripts/build.py

① 原典を読む（読むだけ。docs/ は絶対に書き換えない）
② 検証する（通らなければ data/*.js を一切更新しない）
③ Markdown を HTML にする
④ 被リンク・問い一覧・マトリクス・地雷を集計する
⑤ data/*.js を生成する（許可リストのフィールドだけ）

依存ゼロ。Python 3.11 標準ライブラリのみ。
"""

import hashlib
import io
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import markdown as M
import validate as V

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
HYPO = os.path.join(ROOT, "hypotheses")
DATA = os.path.join(ROOT, "data")
CONFIG = os.path.join(ROOT, "config", "studio.json")
# anchor は原典の逐語。公開物に出さないため別ファイルに分け、.gitignore に入れてある。
ANCHORS = os.path.join(ROOT, "config", "anchors.local.json")

BANNER = "/* AUTO-GENERATED by scripts/build.py — DO NOT EDIT */"


# ── ① 原典 ──────────────────────────────────────
def check_corpus_health():
    """既知の欠損を警告する。**直さない。**（非目標）

    原典は OCR と分割の都合で壊れている箇所がある。黙って通すと、
    引用の照合が謎に失敗したときに原因を探せなくなる。
    """
    warnings = []

    def raw(rel):
        p = os.path.join(DOCS, rel.replace("/", os.sep))
        if not os.path.exists(p):
            return None
        return io.open(p, encoding="utf-8").read()

    t = raw("原理講論/前編/03_堕落論.md")
    if t and "## 後編緒論" in t:
        warnings.append("原理講論/前編/03_堕落論.md に後編の緒論が混入している")

    t = raw("原理講論/前編/07_予定論.md")
    if t and "第一節" not in t:
        warnings.append("原理講論/前編/07_予定論.md の第一節が欠落している")

    t = raw("原理講論/後編/04_復帰歴史の各時代とその年数の形成.md")
    if t and "第三章 摂理歴史の" in t:
        warnings.append("原理講論/後編/04_… の H1 と本文の章題が一致しない")

    t = raw("原理講論/前編/01_総序.md")
    if t and re.search(r"^## 後編\s*$", t, re.M):
        warnings.append("原理講論/前編/01_総序.md に空の ## 後編 が残っている")

    return warnings


# ── ⑤ 出力の許可リスト ──────────────────────────
def pick_article(art, body_html, plain, chars, backlinks):
    """design の許可リストに挙げたフィールドだけを出力する。

    **anchor を出力しない。** 原典の逐語であり、検証にしか要らない。
    出さなければ、生成物に載る原典の逐語は :::quote の引用だけに限定される。
    """
    fm = art["fm"]
    return {
        "slug": art["slug"],
        "title": fm["title"],
        "claim": fm["claim"],
        "lens": fm["lens"],
        "topics": fm["topics"],
        "mode": fm["mode"],
        "terrain": fm["terrain"],
        "science": fm["science"],
        "falsifiers": fm["falsifiers"],
        "questions": fm["questions"],
        "related": fm["related"],
        "backlinks": backlinks,
        "sources": [{"label": s.get("label", ""), "file": s.get("file", "")}
                    for s in fm["sources"]],
        "mines": [{"id": m["id"], "touches": bool(m["touches"]),
                   "reason": m.get("reason", "")} for m in fm["mines"]],
        "known": list(fm["known"]),
        "bodyHtml": body_html,
        "plain": plain,
        "chars": chars,
    }


def pick_studio(studio):
    """語彙定義。anchor は落とす。"""
    return {
        "topics": studio["topics"],
        "lenses": studio["lenses"],
        "modes": studio["modes"],
        "terrains": studio["terrains"],
        "mines": [{"id": m["id"], "position": m["position"], "note": m["note"],
                   "sourceLabel": m["source"].get("label", "")}
                  for m in studio["mines"]],
        "known": [{"id": k["id"], "pairing": k["pairing"],
                   "sourceLabel": k["source"].get("label", "")}
                  for k in studio["known"]],
    }


def render_js(varname, payload):
    body = json.dumps(payload, ensure_ascii=False, indent=1)
    return "%s\nwindow.%s = %s;\n" % (BANNER, varname, body)


def write_all(files):
    """4 本まとめて書く。**全部を組み立ててから書き込みに入る。**

    順に open("w") すると、途中で落ちたとき新しい hypotheses.js と古い studio.js が
    並ぶ。切り詰め直後に落ちれば 0 バイトの .js が残り、画面が表示できなくなる。
    一時ファイルへ書いてから os.replace で差し替える。
    """
    tmp = []
    try:
        for name, text in files:
            path = os.path.join(DATA, name)
            tmp_path = path + ".tmp"
            with io.open(tmp_path, "w", encoding="utf-8") as fh:
                fh.write(text)
            tmp.append((tmp_path, path))
        for tmp_path, path in tmp:
            os.replace(tmp_path, path)
        tmp = []
    finally:
        for tmp_path, _ in tmp:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)


# ── Service Worker ──────────────────────────────
# キャッシュする app shell。ここに無いものはネットワークへ行く。
SHELL = [
    "./",
    "index.html",
    "manifest.webmanifest",
    "assets/css/tokens.css", "assets/css/base.css", "assets/css/layout.css",
    "assets/css/components.css", "assets/css/prose.css",
    "assets/js/dom.js", "assets/js/store.js", "assets/js/search.js",
    "assets/js/toc.js", "assets/js/router.js", "assets/js/app.js",
    "assets/js/views/partials.js", "assets/js/views/list.js",
    "assets/js/views/article.js", "assets/js/views/questions.js",
    "assets/js/views/matrix.js", "assets/js/views/mines.js",
    "data/studio.js", "data/hypotheses.js", "data/matrix.js", "data/questions.js",
    "assets/icons/icon-192.png", "assets/icons/icon-512.png",
    "assets/icons/icon-maskable-512.png",
    "assets/icons/apple-touch-icon-180.png", "assets/icons/favicon-32.png",
]

SW_TEMPLATE = """%(banner)s
/* app shell をキャッシュして、オフラインでも開けるようにする。

   版は app shell の中身のハッシュから決まる。手で上げる必要はない。
   中身が変われば版が変わり、古いキャッシュは activate で消える。
   file:// では Service Worker が動かないので、登録は index.html 側で弾いている。 */
const VERSION = '%(version)s';
const CACHE = 'god-thinking-' + VERSION;
const SHELL = %(shell)s;

self.addEventListener('install', function (ev) {
  ev.waitUntil(
    caches.open(CACHE)
      .then(function (c) {
        // **cache: 'reload' が要る。** 既定では addAll がブラウザの HTTP キャッシュを
        // 経由するため、版を上げても古いファイルがそのまま入りうる。
        // 実際それで、新しい版のキャッシュに古い matrix.js が入る事故が起きた。
        return c.addAll(SHELL.map(function (u) {
          return new Request(u, { cache: 'reload' });
        }));
      })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (ev) {
  ev.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.map(function (k) {
        return k === CACHE ? null : caches.delete(k);
      }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('fetch', function (ev) {
  if (ev.request.method !== 'GET') return;
  ev.respondWith(
    caches.match(ev.request).then(function (hit) {
      if (hit) return hit;
      return fetch(ev.request).catch(function () {
        // 画面遷移はハッシュルーティングなので、外れたら index.html を返す
        if (ev.request.mode === 'navigate') return caches.match('index.html');
        throw new Error('offline');
      });
    })
  );
});
"""


def build_sw():
    """sw.js を生成する。版は app shell の中身から決める。

    手でバージョンを上げる作りにすると、上げ忘れて古い画面が出続ける。
    ハッシュにしておけば、中身が変わったときだけ確実に版が変わる。
    """
    h = hashlib.sha256()
    for rel in SHELL:
        if rel == "./":
            continue
        path = os.path.join(ROOT, rel.replace("/", os.sep))
        if os.path.exists(path):
            h.update(rel.encode("utf-8"))
            h.update(io.open(path, "rb").read())
    version = h.hexdigest()[:12]
    body = SW_TEMPLATE % {
        "banner": BANNER,
        "version": version,
        "shell": json.dumps(SHELL, indent=2),
    }
    return version, body


# ── 本体 ────────────────────────────────────────
def main():
    print("仮説工房 ビルド")
    print("=" * 56)

    studio = json.load(io.open(CONFIG, encoding="utf-8"))

    # ① 原典
    corpus = V.load_corpus(DOCS)
    print("原典: %d ファイル読み込み（読むだけ。書き換えない）" % len(corpus))

    for w in check_corpus_health():
        print("  警告: %s" % w)

    # 記事
    paths = sorted(f for f in os.listdir(HYPO) if f.endswith(".md")) if os.path.isdir(HYPO) else []
    articles = [V.load_article(os.path.join(HYPO, f)) for f in paths]
    print("記事: %d 本" % len(articles))

    # 記事が 1 本も無いのを「合格」にすると、hypotheses/ を移動しただけで
    # 生成物が空で上書きされる。検証が唯一の防波堤なので、ここで止める。
    if not articles:
        print("\nhypotheses/ に記事がありません。")
        print("data/*.js は更新していません。")
        return 1

    # ② 検証
    print("-" * 56)
    anchors = V.load_anchors(ANCHORS)
    rep = V.validate_all(articles, studio, corpus, anchors)

    for w in rep.warnings:
        print("  警告: %s — %s" % (w["where"], w["msg"]))

    if rep.errors:
        print("\n検証に失敗しました。%d 件。" % len(rep.errors))
        print("data/*.js は更新していません。\n")
        for e in rep.errors:
            print("  [%s] %s" % (e["code"], e["where"]))
            print("      %s" % e["msg"])
        return 1

    total_checks = sum(rep.checked.get(k, 0) for k in rep.checked if k != "anchor_hits")
    print("検証: 合格")
    print("  検査した項目: %d 件" % total_checks)
    for code in sorted(rep.checked):
        if code == "anchor_hits":
            continue
        print("    %-8s %d 件" % (code, rep.checked[code]))
    print("  原典で照合できた anchor の出現回数: 合計 %d 回"
          % rep.checked.get("anchor_hits", 0))

    # ③ 変換
    print("-" * 56)
    slugs = {a["slug"] for a in articles}
    titles = {a["slug"]: a["fm"]["title"] for a in articles}
    rendered, xref_map = {}, {}
    for art in articles:
        sink, xrefs = [], set()
        html_body = M.render(art["body"], sink=sink, sources=art["fm"]["sources"],
                             titles=titles, xrefs=xrefs)
        rendered[art["slug"]] = (html_body, sink)
        xref_map[art["slug"]] = xrefs

    # ④ 集計
    backlinks = {s: set() for s in slugs}
    for slug, refs in xref_map.items():
        for target in refs:
            if target in backlinks and target != slug:
                backlinks[target].add(slug)
    for art in articles:
        for target in art["fm"]["related"]:
            if target in backlinks and target != art["slug"]:
                backlinks[target].add(art["slug"])

    out_articles, questions = [], []
    for art in articles:
        html_body, _sink = rendered[art["slug"]]
        plain = M.strip_tags(html_body)
        out_articles.append(pick_article(
            art, html_body, plain, V.count_chars(art["body"]),
            sorted(backlinks[art["slug"]])))
        for q in art["fm"]["questions"]:
            questions.append({"text": q, "slug": art["slug"],
                              "title": art["fm"]["title"]})

    # マスは 3 状態。記事の有無が cells の指定より優先する。
    filled_keys = set()
    for topic in studio["topics"]:
        for lens in studio["lenses"]:
            if any(topic in a["topics"] and lens in a["lens"] for a in out_articles):
                filled_keys.add((topic, lens))

    judged = V.validate_cells(studio, filled_keys, rep)
    if rep.errors:
        print("\n空白マスの判断に不足があります。%d 件。" % len(rep.errors))
        print("data/*.js は更新していません。\n")
        for e in rep.errors:
            print("  [%s] %s" % (e["code"], e["where"]))
            print("      %s" % e["msg"])
        return 1

    matrix = []
    for topic in studio["topics"]:
        for lens in studio["lenses"]:
            hits = [a["slug"] for a in out_articles
                    if topic in a["topics"] and lens in a["lens"]]
            cell = {"topic": topic, "lens": lens, "slugs": hits}
            if hits:
                cell["status"] = "filled"
            else:
                j = judged.get((topic, lens))
                cell["status"] = j["status"]
                cell["note"] = j["note"]
            matrix.append(cell)
    filled = sum(1 for c in matrix if c["status"] == "filled")
    planned = sum(1 for c in matrix if c["status"] == "planned")

    # ⑤ 出力
    if not os.path.isdir(DATA):
        os.makedirs(DATA)
    write_all([
        ("hypotheses.js", render_js("HYPOTHESES", out_articles)),
        ("studio.js", render_js("STUDIO", pick_studio(studio))),
        ("matrix.js", render_js("MATRIX", matrix)),
        ("questions.js", render_js("QUESTIONS", questions)),
    ])

    # Service Worker。data/*.js を書いたあとでハッシュを取る。
    version, sw = build_sw()
    with io.open(os.path.join(ROOT, "sw.js"), "w", encoding="utf-8") as fh:
        fh.write(sw)

    print("生成: data/hypotheses.js / studio.js / matrix.js / questions.js")
    print("生成: sw.js（版 %s / app shell %d 件）" % (version, len(SHELL)))
    print("  マトリクス: %d マス中 記事あり %d / 未着手 %d / 該当なし %d"
          % (len(matrix), filled, planned, len(matrix) - filled - planned))
    print("  問い: %d 件" % len(questions))
    print("=" * 56)
    print("完了")
    return 0


if __name__ == "__main__":
    sys.exit(main())
